name: XRTK CI

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - '*'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  validate:
    runs-on: ${{ matrix.includes.os }}
    strategy:
      matrix:
        includes:
          - os: [[self-hosted],[windows]]
            build-targets: [Android,Standalone64,WSAPlayer]
            editor-path: ''
            project-path: ''
          - os: [[self-hosted],[macos]]
            build-targets: [Android]
            editor-path: ''
            project-path: ''

    outputs:
      matrix: ${{ steps.set-build-matrix.outputs.matrix }}

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
          clean: true

      - id: unity-validate
        name: Unity Editor Validation
        uses: xrtk/unity-validate@main

      - id: set-build-matrix
        name: set build matrix
        run: |
          $matrix = '${{ toJSON(matrix) }}' | ConvertFrom-Json
          echo $matrix
          $editorPath = '${{ steps.unity-validate.outputs.editor-path }}'
          $projectPath = '${{ steps.unity-validate.outputs.project-path }}'

          if ([string]::IsNullOrEmpty($editorPath)) {
            echo "failed to find a valid editor path"
            exit 1
          }

          if ([string]::IsNullOrEmpty($projectPath)) {
            echo "failed to find a valid project path"
            exit 1
          }

          $matrix.includes.editor-path = $editorPath
          $matrix.includes.project-path = $projectPath

          $matrixJson = $matrix | ConvertTo-Json -Compress
          $matrixJson.replace('"','\"')
          echo $matrixJson

          echo "::set-output name=matrix::$matrixJson"
        shell: pwsh

      - uses: xrtk/unity-action@main
        name: Project Validation
        with:
          name: 'project-validation'
          editor-path: '${{ steps.unity-validate.outputs.editor-path }}'
          project-path: '${{ steps.unity-validate.outputs.project-path }}'
          args: '-quit -batchmode -executeMethod XRTK.Editor.BuildPipeline.UnityPlayerBuildTools.ValidateProject'

      - uses: actions/upload-artifact@v2
        name: Upload Artifacts
        if: always()
        with:
          name: 'Validation-Results'
          path: '${{ steps.unity-validate.outputs.project-path }}/Builds/Logs'

      - name: Cleanup Job
        run: |
          $logDirectory = "${{ steps.unity-validate.outputs.project-path }}/Builds"

          if (Test-Path -Path $logDirectory) {
            Remove-Item $logDirectory -Force -Recurse
          }
        shell: pwsh

  build:
    needs: validate
    runs-on: ${{ matrix.includes.os }}
    strategy:
      matrix: ${{ fromJSON(needs.validate.outputs.matrix) }}

      max-parallel: 1

    steps:
      - uses: xrtk/unity-action@main
        name: '${{ matrix.includes.build-target }}-Tests'
        with:
          name: '${{ matrix.includes.build-target }}-Tests'
          editor-path: '${{ matrix.includes.editor-path }}'
          project-path: '${{ matrix.includes.project-path }}'
          build-target: '${{ matrix.includes.build-target }}'
          args: '-batchmode -runEditorTests'

      - uses: xrtk/unity-action@main
        name: '${{ matrix.includes.build-target }}-Build'
        with:
          name: '${{ matrix.includes.build-target }}-Build'
          editor-path: '${{ matrix.includes.editor-path }}'
          project-path: '${{ matrix.includes.project-path }}'
          build-target: '${{ matrix.includes.build-target }}'
          args: '-quit -batchmode -executeMethod XRTK.Editor.BuildPipeline.UnityPlayerBuildTools.StartCommandLineBuild'

      - name: Zip Artifacts
        if: always()
        run: |
          $artifacts = "${{ matrix.includes.project-path }}/Builds"

          if (Test-Path -Path $artifacts) {
            Compress-Archive -Path "$artifacts/*" -DestinationPath ${{ github.workspace }}/${{ matrix.includes.build-target }}-Artifacts.zip -Force
            Remove-Item $artifacts -Force -Recurse
          }
        shell: pwsh

      - uses: actions/upload-artifact@v2
        name: Upload Artifacts
        if: always()
        with:
          name: '${{ matrix.includes.build-target }}-Artifacts'
          path: '${{ github.workspace }}/${{ matrix.includes.build-target }}-Artifacts.zip'

  publish:
    if: ${{ github.ref == 'refs/heads/main' || github.base_ref == 'main' }}
    needs: build
    runs-on:  ubuntu-latest

    steps:
      - uses: xrtk/upm-release@main
        name: publish upm package
        with:
          upm-username: 'xrtk-build-bot'
          upm-email: 'xrtk-build-bot@xrtk.io'
          upm-server-address: 'http://upm.xrtk.io:4873'
          upm-auth-token: '${{ secrets.UPM_CREDENTIALS }}'
          github-username: 'XRTK-Build-Bot'
          github-pat: '${{ secrets.GITHUB_PAT }}'
          github-token: '${{ secrets.GITHUB_TOKEN }}'
