name: XRTK CI

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - '*'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  validate:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [windows,macos]

    outputs:
      windows-editor-path: ${{ steps.set-paths.outputs.windows-editor-path }}
      windows-project-path: ${{ steps.set-paths.outputs.windows-project-path }}
      macos-editor-path: ${{ steps.set-paths.outputs.macos-editor-path }}
      macos-project-path: ${{ steps.set-paths.outputs.macos-project-path }}

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
          clean: true

      - id: unity-validate
        name: Unity Editor Validation
        uses: xrtk/unity-validate@main

      - id: set-paths
        name: set build matrix
        run: |
          $editorPath = '${{ steps.unity-validate.outputs.editor-path }}'
          $projectPath = '${{ steps.unity-validate.outputs.project-path }}'

          if ([string]::IsNullOrEmpty($editorPath)) {
            echo "failed to find a valid editor path"
            exit 1
          }

          if ([string]::IsNullOrEmpty($projectPath)) {
            echo "failed to find a valid project path"
            exit 1
          }

          $editorPathName = '${{ matrix.os }}-editor-path'
          $projectPathname = '${{ matrix.os }}-project-path'

          echo "::set-output name=$editorPathName::$editorPath"
          echo "::set-output name=$projectPathname::$projectPath"
        shell: pwsh

      - uses: xrtk/unity-action@main
        name: Project Validation
        with:
          name: 'project-validation'
          editor-path: '${{ steps.unity-validate.outputs.editor-path }}'
          project-path: '${{ steps.unity-validate.outputs.project-path }}'
          args: '-quit -batchmode -executeMethod XRTK.Editor.BuildPipeline.UnityPlayerBuildTools.ValidateProject'

      - uses: actions/upload-artifact@v2
        name: Upload Artifacts
        if: always()
        with:
          name: 'Validation-Results'
          path: '${{ steps.unity-validate.outputs.project-path }}/Builds/Logs'

      - name: Cleanup Job
        run: |
          $logDirectory = "${{ steps.unity-validate.outputs.project-path }}/Builds"

          if (Test-Path -Path $logDirectory) {
            Remove-Item $logDirectory -Force -Recurse
          }
        shell: pwsh

  build:
    needs: validate
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - build-target: Android
            os: windows
            editor-path: ${{ needs.validate.outputs.windows-editor-path }}
            project-path: ${{ needs.validate.outputs.windows-project-path }}
          - build-target: StandaloneWindows64
            os: windows
            editor-path: ${{ needs.validate.outputs.windows-editor-path }}
            project-path: ${{ needs.validate.outputs.windows-project-path }}
          - build-target: WSAPlayer
            os: windows
            editor-path: ${{ needs.validate.outputs.windows-editor-path }}
            project-path: ${{ needs.validate.outputs.windows-project-path }}
          - build-target: Android
            os: macos
            editor-path: ${{ needs.validate.outputs.macos-editor-path }}
            project-path: ${{ needs.validate.outputs.macos-project-path }}
          - build-target: StandaloneOSX
            os: macos
            editor-path: ${{ needs.validate.outputs.macos-editor-path }}
            project-path: ${{ needs.validate.outputs.macos-project-path }}

    steps:
      - uses: xrtk/unity-action@main
        name: '${{ matrix.build-target }}-Tests'
        with:
          name: '${{ matrix.build-target }}-Tests'
          editor-path: '${{ matrix.editor-path }}'
          project-path: '${{ matrix.project-path }}'
          build-target: '${{ matrix.build-target }}'
          args: '-batchmode -runEditorTests'

      - uses: xrtk/unity-action@main
        name: '${{ matrix.build-target }}-Build'
        with:
          name: '${{ matrix.build-target }}-Build'
          editor-path: '${{ matrix.editor-path }}'
          project-path: '${{ matrix.project-path }}'
          build-target: '${{ matrix.build-target }}'
          args: '-quit -batchmode -executeMethod XRTK.Editor.BuildPipeline.UnityPlayerBuildTools.StartCommandLineBuild'

      - name: Zip Artifacts
        if: always()
        run: |
          $artifacts = "${{ matrix.project-path }}/Builds"

          if (Test-Path -Path $artifacts) {
            Compress-Archive -Path "$artifacts/*" -DestinationPath ${{ github.workspace }}/${{ matrix.build-target }}-Artifacts.zip -Force
            Remove-Item $artifacts -Force -Recurse
          }
        shell: pwsh

      - uses: actions/upload-artifact@v2
        name: Upload Artifacts
        if: always()
        with:
          name: '${{ matrix.build-target }}-Artifacts'
          path: '${{ github.workspace }}/${{ matrix.build-target }}-Artifacts.zip'

  publish:
    if: ${{ github.ref == 'refs/heads/main' || github.base_ref == 'main' }}
    needs: build
    runs-on:  ubuntu-latest

    steps:
      - uses: xrtk/upm-release@main
        name: publish upm package
        with:
          upm-username: 'xrtk-build-bot'
          upm-email: 'xrtk-build-bot@xrtk.io'
          upm-server-address: 'http://upm.xrtk.io:4873'
          upm-auth-token: '${{ secrets.UPM_CREDENTIALS }}'
          github-username: 'XRTK-Build-Bot'
          github-pat: '${{ secrets.GITHUB_PAT }}'
          github-token: '${{ secrets.GITHUB_TOKEN }}'
